### ISSUE TITLE
Newton-Raphson method for state estimation

### ISSUE THREAD

**Issue by TonyXiang8787** [PowerGridModel/power-grid-model#369]
Newton-Raphson method should solve the issue in #237

**Comment by mgovers** [comment]
Update 2024/02/08:

Since #438 , Newton-Raphson for state estimation is now in beta as an experimental feature.

Because we do not officially support it yet, nor guarantee its correctness, it is not yet possible to call this feature via the regular API's [`PowerGridModel.calculate_state_estimation`](https://power-grid-model.readthedocs.io/en/stable/api_reference/python-api-reference.html#power_grid_model.PowerGridModel.calculate_state_estimation)).

Instead, call the protected method `PowerGridModel._calculate_state_estimation` with as arguments:
* `calculation_method=CalculationMethod.newton_raphson`
* `experimental_features=power_grid_model.enum._ExperimentalFeatures.enabled`
* any other arguments which are the same arguments as for the iterative linear case.

E.g. someone who would usually call

```py
from power_grid_model import PowerGridModel
from power_grid_model.enum import CalculationMethod

# create input data
model = PowerGridModel(input_data)
model.calculate_state_estimation(calculation_method=CalculationMethod.iterative_linear)
```

may run the Newton-Raphson state estimation by running

```py
from power_grid_model import PowerGridModel
from power_grid_model.enum import CalculationMethod, ExperimentalFeatures_

# create input data
model = PowerGridModel(input_data)
model.calculate_state_estimation(calculation_method=CalculationMethod.newton_raphson, experimental_features=ExperimentalFeatures_.enabled)
```
