### ISSUE TITLE
[FEATURE] In validation function, it still requires power sigma for power sensor

### ISSUE THREAD

**Issue by TonyXiang8787** [PowerGridModel/power-grid-model#501]
In the validation function for state estimation, `power_sigma` is still required. However, we either need `power_sigma`, or `p_sigma` and `q_sigma`.

The validation function should be changed.

See a test case here:

https://github.com/PowerGridModel/power-grid-model-workshop/blob/7ac38f2fb5b7ec42f242fe963be9a92b5404e2df/examples/State%20estimation%20with%20Newton-Raphson%20method.ipynb

**Comment by mgovers** [comment]
I remember that, by design, we decided that `power_sigma` always needs to be provided. At least, it is reflected in the docs in that way: https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#generic-power-sensor . Therefore, this is not a bug report, but a new feature request.

See also the discussion in #409 . that way, there's always a fallback value.

**Comment by TonyXiang8787** [comment]
@mgovers now after my second thought it actually makes sense to require either `power_sigma`, or `p_sigma` and `q_sigma`. Instead of always require `power_sigma`. This is confusing for the user.
