### ISSUE TITLE
[FEATURE] *Direct Handling of Electrical Parameters in JSON Interface*

### ISSUE THREAD

**Issue by scud-soptim** [PowerGridModel/power-grid-model#642]
#### Description
This feature introduces the capability to directly handle electrical parameters (r, x, g, b) within the JSON interface of the Power Grid Model (PGM). This enhancement aims to eliminate the need for conversion between transformer parameters and electrical parameters, thereby improving accuracy and simplifying the data handling process.

#### Detailed Description
1. **Current Process**:
   - In CGMES data, only electrical parameters (r, x, g, b) are provided.
   - A CGMES-PGM converter has been created to transform these electrical parameters into transformer parameters.
   - The Power Grid Model then converts these transformer parameters back into electrical parameters for calculations.

2. **Proposed Change**:
   - Enable the JSON interface of the Power Grid Model to accept electrical parameters (r, x, g, b) directly.
   - Modify the internal data handling and processing functions to work with these electrical parameters without requiring intermediate conversion to transformer parameters.

3. **Benefits**:
   - Increases the accuracy of the data by avoiding multiple conversions.
   - Simplifies the data exchange process between CGMES and PGM.
   - Reduces computational overhead and potential sources of errors.

**Comment by mgovers** [comment]
Hi @sudo-ac , what would you propose the JSON interface would look like? Can you provide an example?

**Comment by mgovers** [comment]
My expectation is that it will not be straightforward to add this without introducing a significant memory overhead unless we have the columnnar data format mentioned in #548 , but we will discuss this in the near future. c.c. @petersalemink95

**Comment by petersalemink95** [comment]
After discussing with the maintainers we concluded the following.

Instead of extending the transformer/3w_transformer we would want to make a new component: generic_branch (naming is pending), which would model branches as a Pi model, i.e. the user can specify:
- k: transformer ratio
- theta: angle shift
- Z_series (r/x)
- Y_shunt (g/b)

@sudo-ac would this work for you?

**Comment by petersalemink95** [comment]
> After discussing with the maintainers we concluded the following.
> 
> Instead of extending the transformer/3w_transformer we would want to make a new component: generic_branch (naming is pending), which would model branches as a Pi model, i.e. the user can specify:
> 
> * k: transformer ratio
> * theta: angle shift
> * Z_series (r/x)
> * Y_shunt (g/b)
> 
> @sudo-ac would this work for you?

Maybe trivial, but `k` should be a float. As requested by @bartgips in #540

**Comment by Jerry-Jinfeng-Guo** [comment]
@petersalemink95 I have some doubt about the transformer ratio. Do you mean to:
- A. have a continuous range for the ratio `k`, instead of a discrete one ...
- B. have a finite many floating ratios, instead of integer ones ...
... as is currently modeled in the tap changer optimizer implementation?

**Comment by Jerry-Jinfeng-Guo** [comment]
@sudo-ac Noted. Thanks for answering. In the current form of PGM tap changer modeling, we are basically doing enumeration to find the optimal tap, although it's less suboptimal than that in reality. If this were to change to solving for a real root (floating point) as requested here, we might need to revisit the core of our tap changer design and work out the mathematics. Eventually it will be a totally different way of optimization than what we are currently doing. Think for example a linear programming or even NR process for tap position.f

**Comment by Jerry-Jinfeng-Guo** [comment]
@sudo-ac Thank you for the clarification. I think there is some mis-understanding from both sides:

> According to my understanding, the solutions for tap calculation always involve the additional voltage that results from the specified or unknown transformer tap and is a complex number (magnitude + angle). Once the additional voltage is determined by the solver, the tap must be calculated from it. 

The additional voltage is a result of changing to a different tap, not the other way around.

> Typically, the determined tap is a floating-point number that must be suitably rounded to an integer. 

The finite tap, which is now an integer, determines the floating point ratio, not the other way around.

> But as mentioned, this requirement should not impact the internal calculations of the program.

If I now understand you correctly, you would want to have floating point ratios next to the integer based tap positions. The floating point ratios are finite and not continuous. Based on these two, the internal would not be affected indeed.

**Comment by petersalemink95** [comment]
> Apologies for my late response. I find the proposal to add a general Pi model for the transformer to be good. I would suggest using the model from Matpower. See https://matpower.org/docs/MATPOWER-manual-8.0.pdf page 27ff. Yes, the ratio should be a float and the shift_angle should be a float as input values. However, Y_shunt and Z_series need to be passed as complex values, so I would prefer the values
> 
> * R_series (Ohm),
> * X_series (Ohm),
> * B_shunt (Siemens)
> * (possibly also G_shunt in Siemens)

That was exactly what I had had in mind. I wrote is as Z_series (r/x), meaning the user would specify R and X, as you mention. My notation wasn't that clear, but good that we're on the same page!

**Comment by petersalemink95** [comment]
@sudo-ac I think @Jerry-Jinfeng-Guo means that the proposed generic_branch component would not fit the current automatic tap changer algorithm, due to having a floating ratio `k`. Would this be an issue for you?

On the long term planning we want to implement the transformer ratio as an unknown in the Newton-Raphson calculations, which will result in floating transformer ratio's. Most of the mathematics are already worked out, but the actual implementation requires some more discussions and is not yet prioritized/planned.

**Comment by petersalemink95** [comment]
In order to add a new component to Power Grid Model the following steps need to be taken:

- [ ] Check if the available input/update/output data suffices (check `power-grid-model/power_grid_model_c/power_grid_model/include/power_grid_model/auxiliary/` `input.hpp` / `update.hpp` / `output.hpp` or in the documentation directly)
- [ ] If not, add the new data format to `code_generation/data/attribute_classes/` `input.json` / `update.json` / `output.json`  + run `code_generation/code_gen.py`
- [ ] Create a new component in a new `power-grid-model/power_grid_model_c/power_grid_model/include/power_grid_model/component/[component].hpp` file that at least inherits from Base, but in this case `GenericBranch` should inherit from `Branch`
- [ ] If necessary: add new enums or exceptions
- [ ] Create the necessary unit tests in `power-grid-model/tests/cpp_unit_tests/test_[component].cpp`
- [ ] Add the `test_[component].cpp` to `power-grid-model/tests/cpp_unit_tests/CMakeLists.txt`
- [ ] Add component to `power_grid_model_c/power_grid_model/include/power_grid_model/all_components.hpp`
- [ ] Not necessary for this component (If necessary update `main_core/topology.hpp` / `input.hpp` / `output.hpp` / `update.hpp`)
- [ ] Add component to `code_generation/data/dataset_class_maps/dataset_definitions.json` + re-run `code_generation/code_gen.py`
- [ ] Add validation test cases to `tests/data`
- [ ] Update input/update data validator for the new component: `src/power_grid_model/validation/validation.py` + add corresponding tests

Note: the order is recommended, but not necessary

**Comment by TonyXiang8787** [comment]
@petersalemink95 please create a new issue with the actual action, namely the new compnent `generic_branch`. And close this one. The discussion here is finished.

**Comment by petersalemink95** [comment]
@sudo-ac Great to hear the work has begun! I've made two new issues, one for `generic_branch` (#729) and one for `generic_branch3` (#730, e.g. three winding transformer).
