### ISSUE TITLE
[BUG] missing validation of k for generic_branch 

### ISSUE THREAD

**Issue by sudo-ac** [PowerGridModel/power-grid-model#797]
**Describe the bug**

The parameter k (ratio of the generic branch) should be validated. Zero values lead to exception errors during calculation.

**To Reproduce**

set k of a generic_branch to zero

**Expected behavior**

Validation check should detect wrong value k

**Solution**
Add check greater than zero in validation.py
def validate_generic_branch(data: SingleDataset) -> list[ValidationError]:
    errors = validate_branch(data, ComponentType.generic_branch)
    errors += all_greater_than_zero(data, ComponentType.generic_branch, "k")
    return errors

**Comment by mgovers** [comment]
Hi @sudo-ac , thank you for finding and reporting this. Is this something you would like to implement?

A couple considerations:

* [ ] The documentation needs to be updated in https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#id9 . Specifically:
  * [ ] the `valid values` column should be `> 0` for attribute `k`.
* [ ] The data validator needs to be updated:
  * [ ] the check mentioned in the description has to be added to `src\power_grid_model\validation\validation.py`
  * [ ] appropriate unit tests need to be created in `tests\unit\validation`
* [ ] TBD: Since it's not an updateable parameter, we can check this in the constructor of the `GenericBranch`. Do you think that makes sense? If so:
  * [ ] please create a new exception type for this in `power_grid_model_c\power_grid_model\include\power_grid_model\common\exception.hpp` with appropriate error message
  * [ ] throw it in the constructor when `k <= 0.0`
  * [ ] add a unit test to the `test_generic_branch.hpp`
  * [ ] add the exception type to `src\power_grid_model\errors.py`
  * [ ] add a message regex interpreter to `src\power_grid_model\core\error_handling.py`
  * [ ] add a unit test to `tests\unit\test_error_handling.py

**Comment by mgovers** [comment]
If possible, we would like to add this this week, so that it can be included in the next version bump. Everything is ready for the version bump except for the final parts of documentation for columnar data, so it's kind of high priority.

If you don't have time for it before that, that's fine, but then we will have top pick it up ourselves, or we'll need to explicitly scope it out of the version (c.c. @petersalemink95 )

**Comment by petersalemink95** [comment]
Updating the component documentation (https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html) should also be part of this issue. The column "valid values" should mention the valid values for `k`, e.g. `!=0`

**Comment by petersalemink95** [comment]
About the suggestion by @mgovers to add a check to the constructor of `GenericBranch`: please don't. We don't check for valid values in the core. That's undefined behavior. That's why we have the input/update validation

**Comment by petersalemink95** [comment]
It is not necessary to be done before the version bump, since it's not a bug in the core itself, but a missing input validation check. Nevertheless, it's of course nice if this is fixed soon :)

**Comment by mgovers** [comment]
Great! cfr. quick discussion with @petersalemink95 , I removed the part on the core implementation from my earlier comment
